### ISSUE TITLE
安装node成功

### ISSUE THREAD

**Issue by shenmou101** [zhufengnodejs/201602free#2]
![f w 3 f s c 9b 9 3](https://cloud.githubusercontent.com/assets/17738224/14248451/4d160932-faa7-11e5-9d0a-ec1437841312.png)

**Comment by lizhanjie1314** [comment]
![5o s gwywxu70pbv3jre6y0](https://cloud.githubusercontent.com/assets/15324887/14248509/843e86aa-faa7-11e5-9203-339bafd47670.png)

**Comment by zhufengnodejs** [comment]
:+1:
